image: "python:3.6"

before_script:
  - python --version
  - pip install virtualenv

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script: 'virtualenv -p `which python3` venv && venv/bin/pip install -r requirements.txt'

test:
  stage: test
  script:
    - 'python -m unittest test_amiller_im'

deploy_app:
  stage: deploy
  tags:
    - ansible
  script:
    - 'ansible-playbook -i environment playbook.yml'
  environment:
    name: amiller.im
    url: https://amiller.im