stages:
  - verify
  - deploy

verify:
  stage: verify
  tags:
    - ansible
  script:
    - 'ls -alh /root && cat /root/.ssh/id_rsa'

deploy_app:
  stage: deploy
  tags:
    - ansible
  script:
    - 'ansible-playbook -i environment playbook.yml'
  environment:
    name: amiller.im
    url: https://amiller.im