stages:
#  - test
  - deploy

deploy:
  stage: deploy
  tags:
    - ansible
  script:
    - 'ansible-playbook -i environment playbook.yml'
  environment:
    name: amiller.im
    url: https://amiller.im
   only:
    - master
