---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: williamyeh/ansible:alpine3

inputs:
  - name: amiller_im_git

params:

run:
  path: amiller_im_git/ci/scripts/get_secrets.sh