---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: eeacms/pylint
    #repository_mirror: TODO
inputs:
  - name: amiller_im_git

params:
  srcDir: amiller_im_git

run:
  path: amiller_im_git/ci/scripts/lint.sh