---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: governmentpaas/spruce
    #repository_mirror: TODO
inputs:
  - name: amiller_im_git

params:
  srcDir: amiller_im_git
