---
resources:
- name: amiller_im_git
  type: git
  source:
    branch: master
    uri: git@gitlab.com:atm08e/amiller.im-py3.git
    private_key: (( vault "secret/gitlab:private" ))

jobs:

- name: lint
  serial: true
  plan:
  - get: amiller_im_git
    trigger: true

  - task: lint
    file: amiller_im_git/ci/tasks/lint.yml
    params:

- name: amiller.im
  serial: true
  plan:
  - get: amiller_im_git
    trigger: true

  - task: get_secrets
    file: amiller_im_git/ci/tasks/get_secrets.yml
    params:
      VAULT_ADDR: https://10.244.0.2:8200
      VAULT_TOKEN: (( vault "secret/vault:root_token" ))

  - task: deploy
    file: amiller_im_git/ci/tasks/ansible_playbook.yml
    params:
      AMILLER_IM_PRIVATE_KEY: (( vault "secret/amiller_im:private" ))
