- hosts: [application]
# TODO nginx configuration and static resources, and static install?
# TODO python3.6 static installation
  tasks:
  - name: Install nginx
    yum:
      name: nginx
      state: latest

  - name: Install htop
    yum:
      name: htop
      state: latest

  - name: Install python3.6
    yum:
      name: python36u
      state: latest

  - name: Install python-devel
    yum:
      name: python36u-devel
      state: latest

  - name: Amiller.im.service file
    template:
      src: templates/amiller.im.service.j2
      dest: /etc/systemd/system/amiller.im.service
      owner: root
      group: root
      mode: '0600'
      daemon_reload: yes

  - name: Amiller nginx reverse proxy
    template:
      src: templates/amiller.im.conf.j2
      dest: /etc/nginx/conf.d/amiller.im.conf
      owner: root
      group: root
      mode: '0600'

  - name: Allow Nginx Permissions on Auto
    user:
      name: nginx
      groups: auto
      append: yes

  - name: Updating Auto Users Directory Permissions
    file:
      path: /home/auto
      state: directory
      mode: 0750

# Need Ansible 2.4.0.0 not in PyPi yet
#  - name: Reload SystemD
#    systemd: daemon_reload=yes