- hosts: [application]
# TODO nginx configuration and static resources, and static install?
# TODO python3.6 static installation
  tasks:
  - name: Install Nginx
    yum:
      name: nginx
      state: latest

  - name: Install Python3.6
    yum:
      name: python36u
      state: latest

  - name: Install Python-Devel
    yum:
      name: python36u-devel
      state: latest